module.exports.Token = require('./token.model');
module.exports.User = require('./user.model');
// eslint-disable-next-line import/no-unresolved
module.exports.Otp = require('./otp.model');
module.exports.Quiz = require('./quiz.model');
module.exports.Profile = require('./profile.model');
module.exports.CreditScore = require('./credit_score');
module.exports.Kyc = require('./kyc.model');
module.exports.Document = require('./document.model');
module.exports.Store = require('./store.model');
module.exports.Card = require('./card.model');
